apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  interval: 10m
  releaseName: elastic-operator
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  valuesFrom:
    - kind: ConfigMap
      name: eck-operator-values