---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
  namespace: mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "6.0.5"
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: mongodb-storage-class
        - metadata:
            name: logs-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            storageClassName: mongodb-storage-class
      template:
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    topologyKey: topology.kubernetes.io/zone
                - weight: 50
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: mongo-admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mongo-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  #additionalMongodConfig:
  #  storage.wiredTiger.engineConfig.journalCompressor: zlib