apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana
  namespace: istio-system
spec:
  encryptedData:
    admin-password: AgCuF6iY6tiKP3EwgQ4DBr/3rqkm4SrnbKlLS5I5XIgzHY2cBg1af8+dgFIetO9iAyskOYrtBZysRROf9PiWPnMmYO3cR2M5nrWji9OFMC7Sub8jdlGYzd+637oh+Ski6tG3rhdaTdmNksPEK6BjGHitLT69rgWMRMXs7PwD+zRWxw543LwDlZt8PAwlewP0CLqwt3y0KSRKZP+08BAo6hVZYZZts8njeuCX5pjftRk0nso+pWJE1dbHW0z8QTRLhfaue8itRT0f52Z6YYbMxJtKXRw1TrqmIFgiXf8BRK7M7JlGHTorkAwwKxaK0/9/9MqCPgtmLOgXEgTO3uG6VV+Fhim8QQB23Uc8MWyCaw/7IO5+EyUWLi9meWZg6PtD14+XHmZMpyCQnfXObSEJuHh0Pa4xeXJXl9ZPXmQ19HgxAt1P9NkosrdZeo2QZU22q9b0UGuJl6uPX8uUZJk6TQotLJSB1mp/erb+od9Lo410miAWVzIGMpTLBnS5c9a8zC7pqkXrNKnC6oENX1kpAmRhYkGd8Kzw1geA4yD3nkYYDtbNL7/sPLc6fiOZqZYuTtXTgqEzYmZe0elrYYZuHssuO64H80NqVPiFWfOtlaAhjLaSpb0dpmvgYBbnTuKLY7VpU2fja/tzJ1zLOkA3CJZ608vF8mfsFo578JrHFVmzFlKWUcjPh9O2Rrl84WdhXonVb3f1JaAtBQ==
    admin-user: AgA9ZiFMoGKG8ZoGhrb/3f4Su1qRY95X4eRiBTgGo/cYhT+LTHibHbzzcRIjFx3EqoWA9hslxRDzYb3pKYBzE5/m75TliaJVgLNaskMH5AEOJOHAigOW+zvDGQCN8AUndwm3+/lhsERk9pE1crfb+CK31YTk/PN18Qj4Rztb9Naw/DijVrkL5Pj9+aEZ/ZOfDGw7sqC09Li+j2Mi6sWkGZjhBdv7vXOa15E4z29496uAsV/7WmDCW6lEeTIQiIaXFMdnQBco/LEakhS5rQjP4H/NpGXNS8AQbe6sBQ+HybAvqwDTF/gLE/VRU/fVEkmisNfz3WxVv6P/TT5UxkGYCRBDF1Ra4NUU9XGWsDZYKItHjf11adj+Q/xVuz0i5iLHPC5aB6O/oiNXqwG+NoEVvwtwqGCSdNd0eLwYR7aJjceMEcYHnq0HrrcrXdLrKjAvWyv+MoXFq5cGnbPAFkJ7QKBZtNs9xOYCwFgeDz5kdzs0tXB5wH/m8G095hf1Rc1Vh4ZsUQJXL6mGj0Bi8xSCAFzDf6qnSyu/YzliApiOTlqXTkhEkc0wJshHMNRpcgG/t5D/xuxi6dSWNV5vuevknNv0qjwI7SYkfPjZ4jIrZCpxHqCKnUZmrHFmDV3I1ugCAN71iGJ186t/D8pfoIaLCDsG7tMEWFIxHmKILAAe5WJzC7UdjTIVzAAqYrda4W2br8SFa3EhccUaEw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana
      namespace: istio-system
    type: Opaque
---
