apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eck-stack
resources:
- eck-repository.yaml
- eck-elasticsearch-release.yaml
- eck-kibana-release.yaml
- eck-logstash-release.yaml
#- eck-filebeat-release.yaml
configMapGenerator:
  - name: kibana-values
    files:
      - values.yaml=eck-kibana-values.yaml
  - name: logstash-values
    files:
      - values.yaml=eck-logstash-values.yaml
  - name: filebeat-values
    files:
      - values.yaml=eck-filebeat-values.yaml
  - name: elasticsearch-values
    files:
      - values.yaml=eck-elasticsearch-values.yaml
configurations:
  - kustomizeconfig.yaml