kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: default-ssd-storage-zrs
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_ZRS
  fsType: xfs
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
